all:	prova	mylsConFork1 myGrepConFork-ridStError myCatConFork mycat padreFigliNipotiConExec
prova:	prova.c
	gcc -Wall prova.c -o prova
mylsConFork1:	mylsConFork1.c
	gcc -Wall mylsConFork1.c -o mylsConFork1
myGrepConFork:	myGrepConFork.c
	gcc -Wall myGrepConFork.c -o myGrepConFork
myCatConFork:	myCatConFork.c
	gcc -Wall myCatConFork.c -o myCatConFork
mycat:	mycat.c
	gcc -Wall mycat.c -o mycat
padreFigliNipotiConExec:	padreFigliNipotiConExec.c
	gcc -Wall padreFigliNipotiConExec.c -o padreFigliNipotiConExec