all: parametri1 parametri2 commentato provaBUFSIZ contaOccorrenze
parametri2: parametri2.c
	gcc -Wall parametri2.c -o parametri2
parametri1: parametri1.c
	gcc -Wall parametri1.c -o parametri1
commentato: commentato.c
	gcc -Wall commentato.c -o commentato
provaBUFSIZ: provaBUFSIZ.c
	gcc -Wall provaBUFSIZ.c -o provaBUFSIZ
contaOccorrenze: contaOccorrenze.c
	gcc -Wall contaOccorrenze.c -o contaOccorrenze
