all: padreFiglioConStatus padresenzafiglio padreFiglioConStatus1 provaValoriWait padreFigliMultipli padreFigliConSalvataggioPID
padreFiglioConStatus: padreFiglioConStatus.c
	gcc -Wall padreFiglioConStatus.c -o padreFiglioConStatus
padresenzafiglio: padresenzafiglio.c
	gcc -Wall padresenzafiglio.c -o padresenzafiglio
padreFiglioConStatus1: padreFiglioConStatus1.c
	gcc -Wall padreFiglioConStatus1.c -o padreFiglioConStatus1
provaValoriWait: provaValoriWait.c
	gcc -Wall provaValoriWait.c -o provaValoriWait
padreFigliMultipli: padreFigliMultipli.c
	gcc -Wall padreFigliMultipli.c -o padreFigliMultipli
padreFigliConSalvataggioPID: padreFigliConSalvataggioPID.c
	gcc -Wall padreFigliConSalvataggioPID.c -o padreFigliConSalvataggio
