all:	provaPipe-bis	pipe-SenzaClose		pipe-Generico1

provaPipe-bis:	provaPipe-bis.c
	gcc -Wall provaPipe-bis.c -o provaPipe
pipe-SenzaClose:	pipe-SenzaClose.c
	gcc -Wall pipe-SenzaClose.c -o pipe-provaPipe
pipe-Generico1:		pipe-Generico1.c
	gcc -Wall pipe-Generico1.c -o pipe-Generico1